name: Release

on:
  push:
    tags:
      - 'v*'
env:
  BUILD_TMP: ./build-tmp

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kanto
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout suite-connector
        uses: actions/checkout@v2
        with:
          repository: eclipse-kanto/suite-connector
          path: ${{ env.BUILD_TMP }}/suite-connector'
          ref: ${{ github.ref }}
          token: ${{ secrets.WF_AUTH }}
      - name: Checkout container-management
        uses: actions/checkout@v2
        with:
          repository: eclipse-kanto/container-management
          path: ${{ env.BUILD_TMP }}/container-management
          ref: ${{ github.ref }}
          token: ${{ secrets.WF_AUTH }}
      - name: Checkout file-upload
        uses: actions/checkout@v2
        with:
          repository: eclipse-kanto/file-upload
          path: ${{ env.BUILD_TMP }}/file-upload
          ref: ${{ github.ref }}
          token: ${{ secrets.WF_AUTH }}
      - name: Checkout software-update
        uses: actions/checkout@v2
        with:
          repository: eclipse-kanto/software-update
          path: ${{ env.BUILD_TMP }}/software-update
          ref: ${{ github.ref }}
          token: ${{ secrets.WF_AUTH }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: ~> 1.5
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
